server:
  port: 8002

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
  application:
    name: springclouddemo-eureka-client

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client: 
    healthcheck: 
      enabled: true
    serviceUrl: 
#     指定服务注册中心的地址
      defaultZone: http://localhost:8001/eureka/
